# Generated by Django 4.1.6 on 2023-02-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NgoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(max_length=100)),
                ('ngo_sector', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='philDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phil_name', models.CharField(max_length=100)),
                ('phil_email', models.CharField(max_length=100)),
                ('phil_phoneNo', models.CharField(max_length=100)),
                ('phil_interest', models.CharField(max_length=300)),
            ],
        ),
    ]
