# Generated by Django 4.1.6 on 2023-02-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngodb',
            name='ngo_fundingNeeds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ngodb',
            name='ngo_goal',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='ngodb',
            name='ngo_loc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ngodb',
            name='ngo_prevWork',
            field=models.CharField(default='', max_length=300),
        ),
    ]
